services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  SvenPetersen\Twitter2News\:
    resource: '../Classes/*'

  SvenPetersen\Twitter2News\Command\ImportTweetsCommand:
    tags:
      - name: 'console.command'
        command: 'twitter2news:import-tweets'
        description: 'Imports tweets for a given username as news entites'
